spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhhlbjshop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 914121
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181

